[package]
name = "examples"
version = "0.2.1"
edition = "2021"

[dependencies]
opencascade = { version = "0.2.1", path = "../crates/opencascade" }
glam = { version = ">=0.23, <=0.24.1", features = ["bytemuck"] }
